#title:Q81 with >=1 3D structure and are located in the mitochondrion and are linked with a disease
#ac:Q09013
SELECT distinct ?entry WHERE {
  ?entry :classifiedWith term:KW-0002 . # 3D-structure
  ?entry :isoform/:localisation/:in/:childOf term:SL-0173 . #mitochondrion
  ?entry :isoform/:medical/rdf:type :Disease.
}