#title:Q16 with a mature chain <= 100 amino acids which are secreted and do not contain cysteines in the mature chain
#pending
#ac:P22352,P49908,P59796
SELECT distinct ?entry WHERE{
{SELECT distinct ?entry WHERE  {
  ?entry :isoform ?iso.
  ?iso :sequence/:length ?len;:localisation/:in/:related/:childOf term:SL-0243
  FILTER (?len<1000)
}}
{SELECT distinct ?entry WHERE  {
  ?entry :isoform ?iso.
  ?iso :modifiedResidue/rdf:type :NonStandardAminoAcid
}}
}
