#title:Q34 with >=1 homeobox domain and with >=1 variant in the homeobox domain(s)
#pending
#ac:A2RU54,A6NCS4,A6NFQ7,A6NHT5,A6NJ46,A6NJG6,A6NJT0,A6NLW8,A6NMT0,A6NNA5
SELECT distinct ?entry  WHERE {
    ?entry :isoform ?iso.
    
# with >=1 homeobox domain    
    ?iso  :region  ?st1.
    ?st1 :in term:DO-00312;:start ?start;:end ?end.

# with >=1 variant
    ?iso  :variant  ?st2.
    ?st2 a :SequenceVariant;:start ?variant.

# one variant in the homeobox domain
    FILTER (?variant >=?start && ?variant <=?end)
}
