#title:Q49 with >=1 variants of the types "A->R" or "R->A"
#ac:O00222,O00330,O14556,O14639,O14827,O14828,O15061,O15164,O15357,O43822
SELECT distinct ?entry WHERE  {
  ?entry :isoform/:variant ?statement.
  {?statement :original "A"^^xsd:string;:variation "R"^^xsd:string}
  UNION
  {?statement :original "R"^^xsd:string;:variation "A"^^xsd:string}
}