#title:Q50, Proteins which are expressed in brain according to IHC 
#     but not expressed in brain according to microarray
# ECO_0000045 as IHC, ECO_0000104 as EST and ECO_0000220 as microarray
#pending
#ac:
#tags:selected
SELECT distinct ?entry WHERE {
 ?entry :isoform ?iso.

# not expressed in brain according to microarray 
  ?iso :negativeExpression ?s1.
  ?s1 :in/:childOf  term:TS-0095;:withEvidence/:experimentalContext/:detectionMethod term:ECO_0000220.

# remove positive expression in children Of Brain for Microarray
  FILTER NOT EXISTS{  
    ?iso :expression ?s.
    ?s :in/:childOf term:TS-0095;:withEvidence/:experimentalContext/:detectionMethod term:ECO_0000220.
  }

# expressed in brain according to IHC
  ?iso :expression ?s2.
  ?s2 :in/:childOf  term:TS-0095;:withEvidence/:experimentalContext/:detectionMethod term:ECO_0000045.
}
