#title:Q53  which are involved in cell adhesion according to GO with 
#     an evidence not IAE and not ISS
#using :notIn partition
#pending 
#ac:Q86UP0,Q86UP6,Q86UX7,Q75N03,Q76LX8,Q7L5Y9
#tags:selected
SELECT distinct ?entry WHERE {
 ?entry  :isoform/:function ?statement.
 ?statement :in / :childOf term:GO_0007155;:withEvidence/:code/:notIn :IEA,:ISS
}
