#title:Q63 which have >=1 RRM RNA-binding domain and either no GO "RNA binding" other a GO "RNA binding" with evidence IEA or ISS
#pending
#ac:A0AV96,A6NDY0,A6NEQ0,A6NFN3,A6PVI3,O14979,O15042,O15047,O15056,O43426 
SELECT distinct ?entry  WHERE {
 ?entry :isoform ?iso
 {
#>=1 RRM RNA-binding domain 
  ?iso :region/:in term:DO-00581.

#GO "RNA binding" with evidence IEA or ISS 
  FILTER NOT EXISTS {
   ?iso :function/:in term:GO_0003723
  }
 }UNION{
#>=1 RRM RNA-binding domain 
  ?iso :region/:in term:DO-00581.

#GO "RNA binding" with evidence IEA or ISS 
  ?iso :function ?s1.
  ?s1 :in term:GO_0003723;:withEvidence/:code ?type.
  values ?type {:IEA :ISS} 

 }
}
