#title:Q65 Proteins with >1 catalytic activity
#pending
#ac:A1Z1Q3,A4D256,A6NGU5,O00217,O00748,O00763,O14638,O14744,O14756,O14975
SELECT distinct ?entry    WHERE  {
  ?ec a :EnzymeClassificationOntology.
  ?entry :classifiedWith ?ec
}GROUP BY ?entry HAVING (count(?ec)>1)
