#Proteins that are not highly expressed in liver at embryo stage
SELECT distinct ?entry WHERE {
  ?entry :isoform/:expression ?statement.
  ?statement :in/:childOf  term:TS-0564;:withEvidence ?evidence.
  ?evidence :expressionLevel/:notIn :High;:experimentalContext/:developmentalStage term:HsapDO_0000002.
}

