#Proteins that are not highly expressed in liver at embryo stage
PREFIX : <http://nextprot.org/rdf#>
PREFIX term: <http://nextprot.org/rdf/terminology/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT distinct ?entry WHERE {
  ?entry :isoform/:expression ?statement.
  ?statement :in/:childOf  term:TS-0564;:evidence ?withEvidence.
  ?withEvidence :expressionLevel/owl:disjointWith :High;:experimentalContext/:developmentalStage term:HsapDO_0000002.
}

