#Q13 with a protein kinase domain but no kinase activity
PREFIX : <http://nextprot.org/rdf#>
PREFIX term: <http://nextprot.org/rdf/terminology/>
SELECT distinct ?entry WHERE {
  ?entry :isoform/:regions/:in term:DO-00529.
  FILTER NOT EXISTS{
   ?entry :isoform/:classifiedWith/:childOf term:2.7.-.-
  }
}