#Q14 with 2 SH3 domains and 1 SH2 domain
PREFIX : <http://nextprot.org/rdf#>
PREFIX term: <http://nextprot.org/rdf/terminology/>
select distinct ?entry  where{
?entry :isoform ?iso.
#with 1 SH1 
  {select ?iso where{?iso :regions ?stat1. ?stat1 :in term:DO-00614}GROUP BY ?iso  HAVING(count( ?stat1)=1)}

#with 2 SH2 
  {select ?iso where{?iso :regions ?stat2. ?stat2 :in term:DO-00615}GROUP BY ?iso HAVING(count( ?stat2)=2)}
}GROUP BY ?entry 
