# Q15, Proteins with a PDZ domain that interact with at least 1 protein which is expressed in brain
SELECT distinct ?entry WHERE {
  ?entry :isoform ?iso.
  ?iso :region/:in term:DO-00477;:interaction/:with/:expression/:in/:childOf term:TS-0095
}
