# Q16 with a mature chain <= 100 amino acids which are secreted and do not contain cysteines 
# in the mature chain
# Works quickly with FUSEKI and slowly with Virtuoso
SELECT distinct ?entry WHERE  {
  ?entry :isoform ?iso.
  ?iso :localisation/:in term:SL-0243;:modifiedResidue/rdf:type :NonStandardAminoAcid;:sequence/:length ?len
  FILTER (?len<1000)
}

