#title:Q16 with a mature chain <= 1000 amino acids which are secreted and do not contain cysteines in the mature chain
#pending
#ac:P22352,P49908,P59796
SELECT distinct ?entry WHERE  {
  ?entry :isoform ?iso.
  ?iso :localisation/:in term:SL-0243;:modifiedResidue/rdf:type :NonStandardAminoAcid;:sequence/:length ?len
  FILTER (?len<1000)
}

