#Q16 with a mature chain <= 100 amino acids which are secreted and do not contain cysteines 
#    in the mature chain
#SELECT distinct ?entry WHERE  {
#  ?entry :isoform ?iso.
#  ?iso :localisation/:in term:SL-0243;:modifiedResidue/rdf:type :NonStandardAminoAcid;:sequence/:length ?len
#  FILTER (?len<100)
#}

SELECT distinct ?entry WHERE{
{SELECT distinct ?entry WHERE  {
  ?entry :isoform ?iso.
  ?iso :sequence/:length ?len;:localisation/:in/:related/:childOf term:SL-0243
  FILTER (?len<100)
}}

{SELECT distinct ?entry WHERE  {
  ?entry :isoform ?iso.
  ?iso :modifiedResidue/rdf:type :NonStandardAminoAcid
}}
}