#Q16 with a mature chain <= 100 amino acids which are secreted and do not contain cysteines 
#    in the mature chain
PREFIX : <http://nextprot.org/rdf#>
PREFIX term: <http://nextprot.org/rdf/terminology/>
