#Q16 with a mature chain <= 100 amino acids which are secreted and do not contain cysteines 
#    in the mature chain
SELECT distinct ?entry WHERE  {
  ?entry :classifiedWith term:KW-0964;:isoform ?iso.
  ?iso :modifiedResidue/rdf:type :NonStandardAminoAcid;:length ?len
  FILTER (?len<100)
}