# Q20, Proteins with >=2 HPA antibodies whose genes are located on chromosome 21 and that are 
#      highly expressed at IHC level in heart
SELECT distinct ?entry WHERE {
# expressed in brain according to IHC
  ?entry :isoform/:expression ?s1.
  ?s1 :in/:childOf  term:TS-0445;:evidence/:experimentalContext/:detectionMethod term:ECO_0000045.
}
  
