#title:Q24 with >1 reported gold interaction 
#pending
#ac:A0AVK6,A0FGR8,A0FGR9,A1A4S6,A5D8V7,A5PKW4,A5YKK6,A7E2Y1,A7KAX9,A7MCY6
select distinct ?entry  where {
  ?entry :isoform/:interaction ?interaction.
  ?interaction :with ?interactant;:quality :GOLD
} order by ?entry