#title:Q3 with >=37 transmembrane region
select distinct ?entry where{
 ?entry :isoform ?iso.
   ?statement a :TransmembraneRegion.
   ?iso :topology ?statement
}GROUP BY ?entry ?iso HAVING(count( ?statement)>=37)
#ac:Q9H5I5

