#Q34 with >=1 homeobox domain and with >=1 variant in the homeobox domain(s)
PREFIX : <http://nextprot.org/rdf#>
PREFIX term: <http://nextprot.org/rdf/terminology/>
SELECT distinct count(?entry)  WHERE {
    ?entry :isoform ?iso.
    
# with >=1 homeobox domain    
    ?iso  :regions  ?st1.
    ?st1 :in term:DO-00312;:start ?start;:end ?end.

# with >=1 variant
    ?iso  :variant  ?st2.
    ?st2 a :SequenceVariant;:start ?variant.

# one variant in the homeobox domain
    FILTER (?variant >=?start && ?variant <=?end)
}