# Q35 Proteins located in the mitochondrion and which is an enzyme
SELECT distinct  ?entry  WHERE  {
# we should care about related terms hierarchy 
# term:SL-0173 :related/:childOf* ?mito.
  ?entry :classifiedWith/rdf:type :EnzymeClassification.
  ?entry :isoform/:localisation/:in/:childOf term:SL-0173  
}

