# Q38 with >=1 selenocysteine in their sequence
# uniprot search, database:(type:nextprot) AND annotation:(type:non_std)
SELECT distinct ?entry WHERE  {
  ?entry :isoform/:modifiedResidue/rdf:type :NonStandardAminoAcid
}
