#Q4, Proteins highly expressed in brain but not expressed in testis
SELECT distinct ?entry WHERE {
# highly expressed in brain
  ?entry :isoform/:expression ?s1.
  ?s1 :in/:childOf  term:TS-0095;:evidence/:expressionLevel :High.

# not expressed in testis
  ?entry :isoform/:expression ?s2.
  ?s2 :in/:childOf  term:TS-1030;:evidence/:expressionLevel :Negative.
}order by ?entry 
