# Q40 that are enzymes and with >=1 mutagenesis that "decrease" or "abolish" activity 
SELECT distinct ?entry ?comment WHERE  {
  ?entry :classifiedWith/rdf:type :EnzymeClassification. 
  ?entry :isoform/:mutation ?statement.
    ?statement rdf:type :MutagenesisSite;rdfs:comment ?comment
  FILTER regex(?comment, '(decrease|abolish).*activity','i')
}
