# Q41 that are annotated with GO "F" terms prefixed by "Not" 
PREFIX : <http://nextprot.org/rdf#>
SELECT distinct ?entry  WHERE  {
  ?entry :isoform/:function ?statement.
  ?statement a :GoMolecularFunction;:evidence/:negative "true"^^xsd:boolean.
}
