# Q48 with >=1 variants of the type "C->" (Cys to anything else) 
#     that are linked to >=1 disease
# medical, 
#     is oneOf (:Biotechnology :Disease :Pharmaceutical :Polymorphism )
SELECT distinct ?entry ?v  WHERE  {
  ?entry :isoform ?iso.
  ?iso :variant ?statement;:medical/rdf:type :Disease.
  ?statement :original 'C'^^xsd:string;:variation ?v
}
