# Q48 with >=1 variants of the type "C->" (Cys to anything else) 
#     that are linked to >=1 disease
# medical, 
#     is oneOf (:Biotechnology :Disease :Pharmaceutical :Polymorphism )
PREFIX : <http://nextprot.org/rdf#>
SELECT distinct ?entry ?v ?disease WHERE  {
  ?entry :isoform ?iso.
  ?iso :variant ?statement;:medical ?disease.
  ?statement :original 'C'^^xsd:string;:variation ?v
}
