# Q49 with >=1 variants of the types "A->R" or "R->A"
# :variant is 
#  owl:oneOf (:Variant :AlignmentConflict *:SequenceConflict* :SequenceVariant )
PREFIX : <http://nextprot.org/rdf#>
SELECT distinct ?entry WHERE  {
  ?entry :isoform/:variant ?statement.
  {?statement :original 'A'^^xsd:string;:variation 'R'^^xsd:string;:original ?original}
  UNION
  {?statement :original 'R'^^xsd:string;:variation 'A'^^xsd:string;:original ?original}
}