#Q5 located in mitochondrion and that lack a transit peptide
select distinct ?entry where{
 ?entry :isoform/:localisation/:in/:childOf term:SL-0173
  FILTER NOT EXISTS{ ?entry :classifiedWith term:KW-0809 }
}order by ?entry