#Q53  which are involved in cell adhesion according to GO with 
#     an evidence not IAE and not ISS
#using :notIn partition 
SELECT distinct ?entry WHERE {
 ?entry  :isoform/:function ?statement.
 ?statement :in term:GO_0007155;:withEvidence/:code/:notIn :IEA,:ISS
}
