#Q53  which are involved in cell adhesion according to GO with 
#     an evidence not IAE and not ISS
SELECT distinct ?entry WHERE {
 ?entry  :isoform/:function ?statement.
 ?statement :in term:GO_0007155.
  FILTER NOT EXISTS {
    ?statement :withEvidence/:code ?type
    values ?type {:IEA :ISS}
  }
}
