# Q57  which are located in mitochondrion with an evidence other 
#      than HPA and DKFZ-GFP
# WARNING! term:SL-0173 is (this must be inferred) 
#        rdfs:sameAs term:GO:0005739;
#        rdfs:sameAs term:KW-0496; 
SELECT  ?entry   WHERE {
  ?entry :isoform/:localisation ?statement.
    ?statement :in/:childOf term:SL-0173;
               :evidence/:fromXref ?source.
  VALUES ?source { db:HPA db:GFP-cDNA}
}
