# Q63 which have >=1 RRM RNA-binding domain (DO-00581 UniprotDomain) and either no GO "RNA binding" (GO:0003723 go molecular function)
#     other a GO "RNA binding" with evidence IEA or ISS 
SELECT distinct ?entry  WHERE {
 ?entry :isoform ?iso
 {
#>=1 RRM RNA-binding domain 
  ?iso :region/:in term:DO-00581.

#GO "RNA binding" with evidence IEA or ISS 
  FILTER NOT EXISTS {
   ?iso :function/:in term:GO_0003723
  }
 }UNION{
#>=1 RRM RNA-binding domain 
  ?iso :region/:in term:DO-00581.

#GO "RNA binding" with evidence IEA or ISS 
  ?iso :function ?s1.
  ?s1 :in term:GO_0003723;:evidence/:code ?type.
  values ?type {:IEA :ISS} 

 }
}
