#title:Q7 linked to diseases that are associated with cardiovascular aspects
#ac:A6NCS4,A6NCS4,O00522,O00522,O00522,O14958,O15273,O15273
select distinct ?entry  WHERE {
# get all entries that are disease and are associated with cardiovascular aspects
  ?entry :isoform/:medical/:in/:related/:childOf term:D002318.
}
