# Q73 Proteins with no domain  (got 13917 entries??) 
# eg. Q22 
PREFIX : <http://nextprot.org/rdf#>
SELECT  distinct ?entry   WHERE  {
  ?entry :isoform ?iso.
  OPTIONAL{?iso :region/rdf:type ?region;:region/rdf:type :Domain}
  FILTER (!BOUND(?region))
}

