#Q83, Proteins whose genes are on chromosome N that are expressed 
#     only a single tissue/organ
SELECT  ?entry  (count(?tissue)as ?c)  WHERE {
  ?entry :gene/:chromosome "19"^^xsd:string;:isoform/:expression/:in/rdfs:label  ?tissue.
}group by ?entry    ORDER BY  ?c limit 5

#select  ?entry ?ac ?tissueCount where { 
#  {SELECT  ?entry  (count(?tissue)as ?tissueCount)  WHERE {
#    ?entry :gene/:chromosome "19"^^xsd:string;:isoform/:expression/:in  ?tissue.
#  }group by ?entry    ORDER BY  ?tissueCount limit 5}
#  
#?entry :isoform/:expression/:in/rdfs:label ?ac
#  
#}group by ?entry ?ac ORDER BY  ?tissueCount 


