#Q9 with 3 disulfide bonds and that are not hormones 
SELECT distinct ?entry  WHERE {
 ?statement a :DisulfideBond.
 ?entry :isoform/:modifiedResidue ?statement
 FILTER NOT EXISTS {
   ?entry :classifiedWith term:KW-0372 
 }
}